FROM ubuntu:17.10

ENV DEBIAN_FRONTEND noninteractive

RUN apt update -yq
RUN apt install -yq mysql-server mysql-client

# Fix MySQL binding address
RUN sed -i -e"s/^bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf

ADD ./startup.sh /opt/startup.sh
ADD ./reload.sh /opt/reload.sh
ADD ./icinga2.sql /opt/icinga2.sql
ADD ./icingaweb2.sql /opt/icingaweb2.sql
ADD ./mysqld_logs.cnf /etc/mysql/mysql.conf.d/mysqld_logs.cnf

EXPOSE 3306

CMD ["/bin/sh", "/opt/startup.sh"]
